# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwoZlSz4ExDJ56TwuaFKeH3OUZXbMb2k
"""

import nltk
nltk.download('punkt_tab')

import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

# Sample text
text = "Natural language processing enables machines to understand human languages."

# Tokenize words
tokens = word_tokenize(text)

# Create frequency distribution
freq_dist = FreqDist(tokens)

# Print results
print("Word Frequencies:", freq_dist)
print("Most Common Words:", freq_dist.most_common(5))
print("Vocabulary Size:", len(freq_dist))